Courses taken route
kenneth-rosario/PREMA-RUM pull request #31
Opened 2022-03-21 01:38 UTC by joseriveramorales

2022-03-21 01:51 UTC, joseriveramorales commented on premarum-backend/PreEnrollmentMgmt.Core/Entities/Student.cs
> +    public void AddCoursesTaken(CoursesTaken coursesTaken)
Instead of sending a CoursesTaken object, send the parameters for the CoursesTaken constructor on this function.

2022-03-21 01:51 UTC, joseriveramorales commented on premarum-backend/PreEnrollmentMgmt.Core/Services/StudentService.cs
> +        var student = await _studentValidationService.ValidateStudentExists(studentEmail);
Add a flag for the ValidateStudentFunction to return the Student's coursesTaken. 

Refer to validatePreEnrollmentExists function.

2022-03-21 01:51 UTC, joseriveramorales commented on premarum-backend/PreEnrollmentMgmt.WebApi/Controllers/DTOS/CoursesTakenDTO.cs
> +    public IEnumerable<CoursesTaken> coursesTaken { get; set; }
Don't return the student Id. 
 CourseId and semesterId is enough. for the CoursesTakenDto.

2022-03-23 18:46 UTC, kenneth-rosario commented on premarum-backend/PreEnrollmentMgmt.Core/Services/StudentService.cs
> +        var student = await _studentValidationService.ValidateStudentExists(studentEmail);
We should probably return the ids that got deleted. What do you think?

2022-03-23 18:47 UTC, kenneth-rosario commented on premarum-backend/PreEnrollmentMgmt.WebApi/Controllers/StudentController.cs
> +    public async Task RemoveStudentCoursestaken(
What do you think of returning the list of ids that got deleted?

2022-03-23 18:50 UTC, kenneth-rosario commented on premarum-backend/PreEnrollmentMgmt.WebApi/Controllers/DTOS/Requests/AddCoursesTakenRequest.cs
> +    [Required] public int[] CoursesTakenIds { get; set; }
What about the semesterId?

2022-04-01 15:23 UTC, kenneth-rosario requested changes

2022-04-01 15:23 UTC, kenneth-rosario commented on premarum-backend/PreEnrollmentMgmt.Core/Services/StudentService.cs
> +    private readonly ICourseRepository _courseRepository;
You need to include this in the constructor or it wont get wired up

2022-04-01 15:23 UTC, kenneth-rosario commented on premarum-backend/PreEnrollmentMgmt.Core/Services/StudentService.cs
> +    private readonly ICourseRepository _courseRepository;
You also need to wire it up in startup.cs

2022-04-02 01:19 UTC, kenneth-rosario commented on premarum-backend/PreEnrollmentMgmt.WebApi/Properties/launchSettings.json
> +        "DATABSE_URL": "//postgres:supersecretpassword@localhost:9001/premadb"
Typo

2022-04-02 01:19 UTC, kenneth-rosario commented on premarum-backend/PreEnrollmentMgmt.WebApi/Properties/launchSettings.json
> +        "DATABSE_URL": "//postgres:supersecretpassword@localhost:9001/premadb"
Typo

2022-04-04 21:15 UTC, kenneth-rosario approved these changes

2022-04-04 21:16 UTC, merged